name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to cluster
        run: |
          kubectl --insecure-skip-tls-verify --validate=false apply -f k8s/
          kubectl --insecure-skip-tls-verify rollout restart deployment/flask-api
          kubectl --insecure-skip-tls-verify rollout status deployment/flask-api